set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_LIBRARY_ARCHITECTURE aarch64-linux-gnu)

set(PROJECT_ROOT_DIR "${CMAKE_CURRENT_LIST_DIR}/../..")

set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)

set(CMAKE_SYSROOT ${PROJECT_ROOT_DIR}/toolchain/aarch64-linux-gnu/${CMAKE_LIBRARY_ARCHITECTURE}/sysroot)
set(CMAKE_FIND_ROOT_PATH ${PROJECT_ROOT_DIR}/toolchain/aarch64-linux-gnu/${CMAKE_LIBRARY_ARCHITECTURE}/sysroot)

set(CMAKE_CROSSCOMPILING true)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
